project:
  type: book
  output-dir: docs

lang: fr

book:
  title: "Les statistiques avec R"
  author: "Marc-André Désautels"
  date: today
  language: fr
  output-file: statistiques_avec_r
  downloads: [pdf]
  url: https://desautm.github.io/statistiquesR/
  repo-url: https://github.com/desautm/statistiquesR/
  repo-actions: [edit]
  search: true
  reader-mode: true
  sidebar:
    style: "docked"
    collapse-level: 2
  chapters:
    - index.qmd
    - part: "Les tableaux"
      chapters: 
        - tableaux.qmd
    - part: "Les graphiques"
      chapters: 
        - ggplot2.qmd
    - part: "Les différentes mesures"
      chapters:
        - mesures.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



