project:
  type: book
  output-dir: docs

execute:
  freeze: auto

lang: fr

book:
  title: "Les statistiques avec R"
  author: "Marc-André Désautels"
  date: today
  language: fr
  output-file: statistiques_avec_r
  downloads: [pdf]
  url: https://desautm.github.io/statistiquesR/
  repo-url: https://github.com/desautm/statistiquesR/
  repo-actions: [edit]
  search: true
  reader-mode: true
  sidebar:
    style: "docked"
    collapse-level: 2
  chapters:
    - index.qmd
    - part: "Les probabilités et la combinatoire"
      chapters: 
        - combinatoire.qmd
        - lois_probabilites.qmd
    - part: "Les statistiques descriptives"
      chapters: 
        - tableaux.qmd
        - ggplot2.qmd
        - mesures.qmd
    - part: "L'estimation et les tests d'hypothèses"
      chapters: 
        - estimation.qmd
        - tests-hypotheses.qmd
        

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



